EDGE_WEIGHTS = {
    1: {
        'width': 0,
        'MIN_LENGTH': 2,
        'MAX_LENGTH': 6,
        'STEP_LENGTH': 2,
        'ROOM_CHANCE': 0,
        'ROOM_MIN_WIDTH': 8,
        'ROOM_MAX_WIDTH': 12,
        'ROOM_MIN_HEIGHT': 8,
        'ROOM_MAX_HEIGHT': 12,
    },
    2: {
        'width': 0,
        'MIN_LENGTH': 2,
        'MAX_LENGTH': 6,
        'STEP_LENGTH': 2,
        'ROOM_CHANCE': 0,
        'ROOM_MIN_WIDTH': 3,
        'ROOM_MAX_WIDTH': 5,
        'ROOM_MIN_HEIGHT': 3,
        'ROOM_MAX_HEIGHT': 5,
    },
    3: {
        'width': 12,
        'MIN_LENGTH': 50,
        'MAX_LENGTH': 80,
        'STEP_LENGTH': 1,
        'ROOM_CHANCE': 0,
        'ROOM_MIN_WIDTH': 6,
        'ROOM_MAX_WIDTH': 10,
        'ROOM_MIN_HEIGHT': 6,
        'ROOM_MAX_HEIGHT': 10,
    },
    4: {
        'width': 0,
        'MIN_LENGTH': 2,
        'MAX_LENGTH': 6,
        'STEP_LENGTH': 2,
        'ROOM_CHANCE': 0,
        'ROOM_MIN_WIDTH': 6,
        'ROOM_MAX_WIDTH': 10,
        'ROOM_MIN_HEIGHT': 6,
        'ROOM_MAX_HEIGHT': 10,
    },
    5: {
        'width': 0,
        'MIN_LENGTH': 2,
        'MAX_LENGTH': 6,
        'STEP_LENGTH': 2,
        'ROOM_CHANCE': 0,
        'ROOM_MIN_WIDTH': 6,
        'ROOM_MAX_WIDTH': 10,
        'ROOM_MIN_HEIGHT': 6,
        'ROOM_MAX_HEIGHT': 10,
    },
}